version: "3"

services:
  c9:
    image: "xczh/c9:ubuntu-rolling"
    restart: always
    cap_add:
      - SYS_PTRACE
    # Container Name
    container_name: c9
    # Hostname
    hostname: c9
    ports:
      # WebIDE HTTP Port
      - "8080:80"
      # WebIDE SSH Port
      - "8022:22"
      # EXTERNAL_PORT, if any
      - "6666:6666"
    environment:
      # use for login: root:${Password}
      - C9_AUTH=root:myide
      # EXTERNAL_PORT, if any
      - EXTERNAL_PORT=6666
    volumes:
      # Workspace Root
      - "/tmp/c9:/workspace"
    networks:
      br_ide:
        ipv4_address: 172.30.10.10
        #ipv6_address:

networks:
  br_ide:
    driver: bridge
    #enable_ipv6: true
    ipam:
      driver:default
      config:
      -
        subnet: 172.30.10.0/24