version: "2.4"

services:
  c9:
    image: "xczh/c9:ubuntu-rolling"
    restart: always
    container_name: c9
    hostname: c9
    cap_add:
      - SYS_PTRACE
    ports:
      - "8080:80"
      - "8022:22"
      - "6666:6666"
    environment:
      - C9_AUTH=root:myide
      - EXTERNAL_PORT=6666
    volumes:
      - "/tmp/c9:/workspace"
    networks:
      br_ide:
        # ipv4_address: 172.30.10.10

networks:
  br_ide:
    external: false
    name: br_ide
    # ipam:
    #   driver:default
    #   config:
    #     subnet: 172.30.10.0/24
